FROM moodlehq/moodle-php-apache:7.4-buster

# install french locale for Moodle date/calendar translation
RUN echo 'fr_FR.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen

# Add custom PHP ini
COPY custom-php.ini /usr/local/etc/php/conf.d

# Install Moosh
ARG moosh_archive=moosh_moodle311_2021113000.zip
ARG moosh_url=https://moodle.org/plugins/download.php/25565/$moosh_archive
RUN cd /tmp && curl -O $moosh_url

RUN unzip /tmp/$moosh_archive -d /usr/local/

RUN ln -s /usr/local/moosh/moosh.php /usr/local/bin/moosh

# Install XDebug
RUN pecl install xdebug

COPY xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN docker-php-ext-enable xdebug
